## LDA code setup

In [2]:

import nltk as nltk
import openpyxl as openpyxl
from nltk.corpus import stopwords
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import *
from sklearn.metrics.pairwise import cosine_similarity
from openpyxl import Workbook
import nltk
import pandas as pd
from numpy import array
from collections import Counter
#from gensim.models import Word2Vec

from sklearn.decomposition import LatentDirichletAllocation
import pandas as pd
import nltk
import numpy as np
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from numpy import s_
import datetime


In [94]:
reviews = pd.read_csv('reviews_till_Date.csv')

In [95]:
reviews.head()

Unnamed: 0                                           reviewId  \
0           0  gp:AOqpTOEyU7-40Ras_s2PEETG3BRpqcnX70XPSMadRe3...   
1           1  gp:AOqpTOE8mZw_WPC2DJbWApajZNvT1rwy3EacEG87UcR...   
2           2  gp:AOqpTOE7ocCUUOQQWaUBYc7UPcSDwBbyGF35bdXeUSa...   
3           3  gp:AOqpTOE4axGizzCOXlL9cKplteffne0vG_wtREXlmqZ...   
4           4  gp:AOqpTOFda4wLwvfII1Vo1tvZ3kic07FivwVuS4mPmax...   

               userName                                          userImage  \
0     Adebola Babatunde  https://play-lh.googleusercontent.com/a/AATXAJ...   
1  James maliet manyuat  https://play-lh.googleusercontent.com/a/AATXAJ...   
2      Tofighe Mokhtari  https://play-lh.googleusercontent.com/a-/AOh14...   
3         mehran aslani  https://play-lh.googleusercontent.com/a-/AOh14...   
4         Thelma Smiles  https://play-lh.googleusercontent.com/a-/AOh14...   

                                   content  score  thumbsUpCount  \
0     there should be an option for a chat      3              0   
1                       very fantastic app      5              0   
2                                     Good      5              0   
3                                        🤦      2              0   
4  cool but always having network problems      4              0   

  reviewCreatedVersion                   at replyContent repliedAt  
0               1.0.11  2021-12-02 19:01:45          NaN       NaN  
1               1.0.18  2021-12-02 18:36:37          NaN       NaN  
2               1.0.16  2021-12-02 18:05:22          NaN       NaN  
3               1.0.16  2021-12-02 17:43:50          NaN       NaN  
4               1.0.18  2021-12-02 17:31:46          NaN       NaN

In [96]:
#changing the name of 1st column and the date column
reviews.rename(columns={reviews.columns[0]: "s_no", "at": "date_posted"}, inplace = True)


In [97]:
reviews.head()

s_no                                           reviewId  \
0     0  gp:AOqpTOEyU7-40Ras_s2PEETG3BRpqcnX70XPSMadRe3...   
1     1  gp:AOqpTOE8mZw_WPC2DJbWApajZNvT1rwy3EacEG87UcR...   
2     2  gp:AOqpTOE7ocCUUOQQWaUBYc7UPcSDwBbyGF35bdXeUSa...   
3     3  gp:AOqpTOE4axGizzCOXlL9cKplteffne0vG_wtREXlmqZ...   
4     4  gp:AOqpTOFda4wLwvfII1Vo1tvZ3kic07FivwVuS4mPmax...   

               userName                                          userImage  \
0     Adebola Babatunde  https://play-lh.googleusercontent.com/a/AATXAJ...   
1  James maliet manyuat  https://play-lh.googleusercontent.com/a/AATXAJ...   
2      Tofighe Mokhtari  https://play-lh.googleusercontent.com/a-/AOh14...   
3         mehran aslani  https://play-lh.googleusercontent.com/a-/AOh14...   
4         Thelma Smiles  https://play-lh.googleusercontent.com/a-/AOh14...   

                                   content  score  thumbsUpCount  \
0     there should be an option for a chat      3              0   
1                       very fantastic app      5              0   
2                                     Good      5              0   
3                                        🤦      2              0   
4  cool but always having network problems      4              0   

  reviewCreatedVersion          date_posted replyContent repliedAt  
0               1.0.11  2021-12-02 19:01:45          NaN       NaN  
1               1.0.18  2021-12-02 18:36:37          NaN       NaN  
2               1.0.16  2021-12-02 18:05:22          NaN       NaN  
3               1.0.16  2021-12-02 17:43:50          NaN       NaN  
4               1.0.18  2021-12-02 17:31:46          NaN       NaN

In [111]:
#adjusting the date column to datetime format for filtering purpose in future
reviews["date_posted"] = pd.to_datetime(reviews["date_posted"], format='%Y-%m-%d')

In [112]:
reviews["date_posted"].head()

0   2021-12-02
1   2021-12-02
2   2021-12-02
3   2021-12-02
4   2021-12-02
Name: date_posted, dtype: datetime64[ns]

In [108]:
#testing the date filters
reviews.loc[reviews['date_posted'] >= "2021-12-02"]

s_no                                           reviewId  \
0      0  gp:AOqpTOEyU7-40Ras_s2PEETG3BRpqcnX70XPSMadRe3...   
1      1  gp:AOqpTOE8mZw_WPC2DJbWApajZNvT1rwy3EacEG87UcR...   
2      2  gp:AOqpTOE7ocCUUOQQWaUBYc7UPcSDwBbyGF35bdXeUSa...   
3      3  gp:AOqpTOE4axGizzCOXlL9cKplteffne0vG_wtREXlmqZ...   
4      4  gp:AOqpTOFda4wLwvfII1Vo1tvZ3kic07FivwVuS4mPmax...   
5      5  gp:AOqpTOEq5oxzZAJj1D4ByLrUykIzd3Q1V3UE6Y00LZV...   
6      6  gp:AOqpTOH_UNmZbGx_WV-OGgDeM8mp4NhT_NAH_A2mbGE...   
7      7  gp:AOqpTOFBhPdyhUCw6YDVDWKvOrV0TPLfbUF4_f1s6G8...   
8      8  gp:AOqpTOFWEq0aDq3v1dZVncoVMYkrne31rl-i1UTpUdZ...   
9      9  gp:AOqpTOHRTaIGLof87XFpxALkCj2Nx9JafHwLjrUe9fw...   
10    10  gp:AOqpTOFRLuWFSo2FloftCGR-XEe3YwUaXpaSNys4k4Q...   
11    11  gp:AOqpTOFuVNTXFthpOCxDLIxEPIUhH3Nq4UM7NHnOUl7...   
12    12  gp:AOqpTOGIwyO_Mkg3__RUzmmZROttGU6iK90yO_32zZd...   
13    13  gp:AOqpTOHN7h-SxZv1TyY4lkYVGH8gtqgF3rzRcavqGId...   
14    14  gp:AOqpTOHjS95913JW2di5Y9rJjNvDAwDj-8njefGCpF-...   
15    15  gp:AOqpTOFk7Qn5_OVfml399Q5ElEtEFl3C8cDoMb4LtpK...   
16    16  gp:AOqpTOHOMOy34WjOCmqhSB3lOqhJ3hEKm4pG9YEYx_L...   
17    17  gp:AOqpTOExFGl2vopEOFlYFGuhxyz9Elr_41Kb3Dvyw5Q...   
18    18  gp:AOqpTOGksFAtDO_D2jSPjCPEWpMOpn_p6EOVYnGrm8-...   
19    19  gp:AOqpTOFfA4drvWYYETUwUh0HtIBWaVbGpzhghLFWagw...   
20    20  gp:AOqpTOGjUbMytvQPVLBiYeGW1M-Rx7XWPXXrXkZepzq...   
21    21  gp:AOqpTOExuSvq_gqFhFmMAoXQ62jCyWRKxjt98-OZAm0...   
22    22  gp:AOqpTOGV4Q3o7mU9ZnBAKFNrTSOdVzZv32PnPPVzJqz...   
23    23  gp:AOqpTOF3i5FdiBFVN8g_mVueHkchjW8FHH0qxoCiTVj...   
24    24  gp:AOqpTOHJkrad4fRoDiF2q8UHApAH2wTDEPrzGAKs6uV...   
25    25  gp:AOqpTOGx6EhS5VLh0VgwEBpBfmc23XHm2eXV0RQUTG_...   
26    26  gp:AOqpTOHw7z4jdYvmtkIoiBlJ6N14FJPutbCJ6K20qyK...   
27    27  gp:AOqpTOHXaDcIQpM1ACY1kl9al9rF9f2GMS-9ISjzIuH...   
28    28  gp:AOqpTOELPPVOMwtktXpvXmxCIUBSRZO9wERtWH-hZGk...   
29    29  gp:AOqpTOEgSYQPD0AQB7O_abBBcQ68BfJ_AwmAr4LabZM...   
30    30  gp:AOqpTOHFmN8ExzQFMyyGHwuuQVhc9x86Rjhv2M7P_Wp...   
31    31  gp:AOqpTOGClsGVEcFIN1Q5xCytSXwuoiUNP2iLD1hz4sw...   
32    32  gp:AOqpTOG4lRMCb7cS4mFPNraH5PdRuQ87j7VjJ4Erjn6...   
33    33  gp:AOqpTOFGL6qa2hDxKIHKGByuGj0jBDRWWJBAQriUyE7...   

                              userName  \
0                    Adebola Babatunde   
1                 James maliet manyuat   
2                     Tofighe Mokhtari   
3                        mehran aslani   
4                        Thelma Smiles   
5                    Hussain Alhussain   
6                   Mustapha Hadjoudja   
7                       guard Justice5   
8                        David Dominic   
9              Mashallah Shamsolvaezin   
10                      Melissa Alilou   
11              Abdolrasul Noeibahoosh   
12               Javed khan Javed khan   
13                         masod lotfi   
14                           R{}VER 99   
15               Richard Samwel Yadoma   
16                        srikanth sri   
17                         arvind samy   
18                       Natiinchrist1   
19                        Arpit Saxena   
20                                Nody   
21                         Bittu Verma   
22                         M U R A A D   
23                      Prasanna Kumar   
24                        mr. crazybou   
25                            pete kib   
26                        tekimon Kira   
27                  امیر محمد ابراهیمی   
28                     Muhammad Yousof   
29  Mr.K.Mohammed Touseef Mcom,MA,DCA,   
30                          ravi kumar   
31                        vincent fong   
32                          Hari Kumar   
33                      Vivek Anandhan   

                                            userImage  \
0   https://play-lh.googleusercontent.com/a/AATXAJ...   
1   https://play-lh.googleusercontent.com/a/AATXAJ...   
2   https://play-lh.googleusercontent.com/a-/AOh14...   
3   https://play-lh.googleusercontent.com/a-/AOh14...   
4   https://play-lh.googleusercontent.com/

In [114]:

lemmatizer = nltk.stem.WordNetLemmatizer()

#Step 1: Transform reviews into term doc matrix, lemmatize, remove stop words etc
processed_reviews = []
original_reviews = []
for each_review in reviews["content"]:
    original_reviews.append(each_review)
    review_token = nltk.word_tokenize(each_review.lower())
    review_token = [lemmatizer.lemmatize(token) for token in review_token if token.isalpha()]
    review_token = [token for token in review_token if not token in stopwords.words('english')]
    processed_reviews.append(review_token)


['good']


In [119]:
print(processed_reviews[3])

[]


In [118]:
original_reviews[0:4]

['there should be an option for a chat', 'very fantastic app', 'Good', '🤦']

In [120]:
#tf-idf
Tfidf_input = []
for i in processed_reviews:
    Tfidf_input.append(" ".join(i))

#applying unigram and bigram and keeping term doc frequency = 4
review_vect = TfidfVectorizer(ngram_range=(1,2), min_df=4)
review_vect.fit(Tfidf_input)
review_vect2 = review_vect.transform(Tfidf_input)


In [121]:
print(review_vect2.toarray())
print(review_vect2.toarray().shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(29325, 6371)


In [124]:
#Step 2: Use LDA model to extract topics of each document
terms = review_vect.get_feature_names()
lda = LatentDirichletAllocation(n_components=10).fit(review_vect2)

topic_dict = {}
for topic_idx, topic in enumerate(lda.components_):
    topic_dict[topic_idx] = ",".join([terms[i] for i in topic.argsort()[-10:]])
    print("Topic %d:" % (topic_idx))
    print(",".join([terms[i] for i in topic.argsort()[:-10-1:-1]]))

Topic 0:
great,best,superb,app,application,clubhouse,number,fun,use,wa
Topic 1:
super,waste,platform,app,time,ever,app ever,better,good platform,waste time
Topic 2:
open,gud,club,app,house,poor,club house,one,idea,beautiful
Topic 3:
good,nice,awesome,nice app,amazing,love,app,working,awesome app,amazing app
Topic 4:
ok,excellent,perfect,change,name,عالی,work,option,change name,room
Topic 5:
app,bad,good app,good,cool,loved,experience,bad app,delete,good experience
Topic 6:
worst,useful,app,social,medium,worst app,one,social medium,good one,voice
Topic 7:
app,great app,great,add,fantastic,wonderful,instagram,please,good,option
Topic 8:
like,app,best app,best,dark,mode,error,dark mode,hear,problem
Topic 9:
account,get,interesting,wow,bug,still,code,invite,ca,app


In [122]:
terms = review_vect.get_feature_names()
terms

['aa',
 'aap',
 'aap hai',
 'aapp',
 'aaya',
 'ab',
 'abhi',
 'ability',
 'ability change',
 'able',
 'able access',
 'able add',
 'able change',
 'able connect',
 'able create',
 'able delete',
 'able download',
 'able enter',
 'able follow',
 'able get',
 'able hear',
 'able invite',
 'able join',
 'able link',
 'able listen',
 'able log',
 'able login',
 'able make',
 'able open',
 'able participate',
 'able register',
 'able see',
 'able sign',
 'able talk',
 'able update',
 'able use',
 'abruptly',
 'absolute',
 'absolutely',
 'absolutely awesome',
 'absolutely love',
 'absurd',
 'abt',
 'abuse',
 'abusing',
 'abusive',
 'abusive language',
 'ac',
 'acc',
 'acc ready',
 'accept',
 'acceptable',
 'accepted',
 'accepting',
 'access',
 'access account',
 'access app',
 'access contact',
 'accessibility',
 'accessible',
 'accessing',
 'accidentally',
 'accont',
 'according',
 'according interest',
 'accordingly',
 'account',
 'account able',
 'account account',
 'account activated',
 